# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hyo-Jun Lee
user_description: Pusan National University, Pusan National University B.S. Student in Applied IT and Engineering, Undergraduate Researcher of IoT Laboratory
user_title: PNU ITE IoT Lab.
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  sylvy0815
gplus_username:  lhj3675

# Google-analytics
google-analytics:
  id: "lhj3675"

exclude: ['package.json', 'src' , 'node_modules']
